# -*- coding: utf-8 -*-
# E:\pyqtdesingner > D:\Python\Scripts\pyuic5.exe test.ui -o test.py

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 70, 341, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 30, 301, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(90, 10, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 16, 16))
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 21, 16))
        self.label_12.setObjectName("label_12")
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setGeometry(QtCore.QRect(30, 40, 61, 21))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_2.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_3.setGeometry(QtCore.QRect(30, 110, 61, 21))
        self.listWidget_3.setObjectName("listWidget_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 250, 301, 221))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(80, 10, 111, 16))
        self.label_6.setObjectName("label_6")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_5)
        self.commandLinkButton.setGeometry(QtCore.QRect(220, 90, 81, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(440, 70, 331, 471))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(90, 0, 161, 41))
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 40, 301, 201))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(90, 10, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 16, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 21, 16))
        self.label_13.setObjectName("label_13")
        self.listWidget_4 = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_4.setGeometry(QtCore.QRect(40, 40, 61, 21))
        self.listWidget_4.setObjectName("listWidget_4")
        self.listWidget_5 = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_5.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.listWidget_5.setObjectName("listWidget_5")
        self.listWidget_6 = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_6.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.listWidget_6.setObjectName("listWidget_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(20, 250, 301, 201))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(90, 10, 111, 16))
        self.label_7.setObjectName("label_7")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.frame_6)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(210, 90, 81, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "机械臂控制系统控制界面"))
        self.label_2.setText(_translate("MainWindow", "Small Robot Control"))
        self.label_4.setText(_translate("MainWindow", "当前位置信息"))
        self.label_8.setText(_translate("MainWindow", "x"))
        self.label_9.setText(_translate("MainWindow", "y"))
        self.label_12.setText(_translate("MainWindow", "z"))
        self.label_6.setText(_translate("MainWindow", "发送的位置信息"))
        self.commandLinkButton.setText(_translate("MainWindow", "发送"))
        self.label_3.setText(_translate("MainWindow", "Big Robot Control"))
        self.label_5.setText(_translate("MainWindow", "当前位置信息"))
        self.label_10.setText(_translate("MainWindow", "y"))
        self.label_11.setText(_translate("MainWindow", "x"))
        self.label_13.setText(_translate("MainWindow", "z"))
        self.label_7.setText(_translate("MainWindow", "发送的位置信息"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "发送"))
if __name__=='__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())